import { Teacher } from '../types/teacher';

const now = new Date().toISOString();

export const MOCK_TEACHERS: Teacher[] = [
  {
    id: '1',
    name: 'Abebe Kebede',
    email: 'abebe.kebede@school.edu.et',
    phone_number: '+251-911-123-456',
    subjects: ['Mathematics', 'Physics'],
    school_name: 'Addis Ababa Secondary School',
    region: 'Addis Ababa',
    qualifications: 'B.Sc. Mathematics, M.Sc. Physics Education',
    biography: 'Experienced educator with 12 years in secondary education. Passionate about STEM subjects.',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Abebe',
    created_at: now,
    updated_at: now,
  },
  {
    id: '2',
    name: 'Almaz Tekle',
    email: 'almaz.tekle@school.edu.et',
    phone_number: '+251-922-234-567',
    subjects: ['English', 'Amharic Literature'],
    school_name: 'Bahir Dar Senior School',
    region: 'Amhara',
    qualifications: 'B.A. English Language, Diploma in Education',
    biography: 'Language specialist with 8 years of teaching experience. Dedicated to improving communication skills.',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Almaz',
    created_at: now,
    updated_at: now,
  },
  {
    id: '3',
    name: 'Getnet Assefa',
    email: 'getnet.assefa@school.edu.et',
    phone_number: '+251-933-345-678',
    subjects: ['Biology', 'Chemistry'],
    school_name: 'Mekelle Science Academy',
    region: 'Tigray',
    qualifications: 'B.Sc. Biology, B.Sc. Chemistry',
    biography: 'Science educator focused on practical laboratory learning. 10 years of experience.',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Getnet',
    created_at: now,
    updated_at: now,
  },
  {
    id: '4',
    name: 'Hirut Woldegebriael',
    email: 'hirut.w@school.edu.et',
    phone_number: '+251-944-456-789',
    subjects: ['History', 'Social Studies'],
    school_name: 'Adama Senior Secondary',
    region: 'Oromia',
    qualifications: 'B.A. History, M.A. African Studies',
    biography: 'History enthusiast with 15 years teaching experience. Specializes in African history.',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hirut',
    created_at: now,
    updated_at: now,
  },
  {
    id: '5',
    name: 'Kadir Mohammed',
    email: 'kadir.m@school.edu.et',
    phone_number: '+251-955-567-890',
    subjects: ['Islamic Studies', 'Arabic'],
    school_name: 'Jijiga School of Excellence',
    region: 'Somali',
    qualifications: 'B.A. Arabic Language, Diploma in Religious Studies',
    biography: 'Islamic scholar and language teacher. 9 years of experience in multicultural education.',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kadir',
    created_at: now,
    updated_at: now,
  },
  {
    id: '6',
    name: 'Selamawit Hailemariam',
    email: 'selamawit.h@school.edu.et',
    phone_number: '+251-966-678-901',
    subjects: ['Physical Education', 'Health Science'],
    school_name: 'Hawassa Sports Academy',
    region: 'Southern Nations',
    qualifications: 'B.Sc. Physical Education, Diploma in Sports Management',
    biography: 'Fitness enthusiast and PE teacher. Promotes healthy lifestyle among students.',
    profile_image_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Selamawit',
    created_at: now,
    updated_at: now,
  },
];

export const ETHIOPIAN_REGIONS = [
  'Addis Ababa',
  'Dire Dawa',
  'Affar',
  'Amhara',
  'Benishangul-Gumuz',
  'Gambela',
  'Harari',
  'Oromia',
  'Sidamo',
  'Somali',
  'Southern Nations',
  'Tigray',
];

export const COMMON_SUBJECTS = [
  'Mathematics',
  'English',
  'Amharic',
  'Physics',
  'Chemistry',
  'Biology',
  'History',
  'Geography',
  'Social Studies',
  'Physical Education',
  'Arabic',
  'French',
  'Information Technology',
  'Business Studies',
  'Economics',
  'Accounting',
  'Fine Art',
  'Music',
  'Health Science',
  'Islamic Studies',
];